version: '3.1'

services:
  overpass:
    environment:
      - VIRTUAL_HOST=overpass.test
    image: 'docker-registry.inventi.cz/overpass-api:latest'
    volumes:
      - './db:/overpass_DB'
    networks:
      - default
      - nginx-proxy

networks:
  default:
  nginx-proxy:
    external: yes
